run:
  deadline: 3m

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gochecknoglobals
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

issues:
  exclude-rules:
    # - path: user-token-authenticator\.go
    #   text: "G101: Potential hardcoded credentials"
    #   linters:
    #     - gosec
linters-settings:
  gocyclo:
    min-complexity: 10
